package com.rayneo.x3constellation

import android.content.Context
import android.media.MediaPlayer
import android.os.Handler
import android.os.Looper
import android.speech.tts.TextToSpeech
import android.util.Log
import java.io.File
import java.util.Locale

/**
 * Multi-voice crew announcer. Each department speaks with a distinct voice.
 *
 * Preferred source: pre-generated Fish Audio S2 clips bundled at
 *   assets/voice/<role>/<clipKey>.wav   (generated by tools/generate_fish_audio.py)
 * Fallback: Android TextToSpeech, with a per-role pitch/rate/voice so the three
 * departments still sound like different people even before clips are generated.
 */
class CrewVoices(private val context: Context) {

    enum class Role(val folder: String, val pitch: Float, val rate: Float, val voiceIndex: Int) {
        NAVIGATION("navigation", 1.00f, 1.00f, 0),
        SCIENCE("science", 1.14f, 0.98f, 1),
        ENGINEERING("engineering", 0.82f, 0.95f, 2),
        COMPUTER("computer", 1.28f, 1.06f, 3)
    }

    private var tts: TextToSpeech? = null
    @Volatile private var ready = false
    private var player: MediaPlayer? = null
    private val clipQueue = ArrayDeque<File>()
    private var busy = false
    private val main = Handler(Looper.getMainLooper())

    private companion object { const val TAG = "X3Voice" }

    fun init() {
        if (tts != null) return
        tts = TextToSpeech(context) { status ->
            if (status == TextToSpeech.SUCCESS) {
                runCatching { tts?.language = Locale.US }
                ready = true
                Log.i(TAG, "TTS ready")
            } else {
                Log.w(TAG, "TTS unavailable (status=$status) — relying on Fish/clip audio")
            }
        }
    }

    /**
     * Speak [text] in [role]'s voice. Priority:
     *   1) bundled clip  assets/voice/<role>/<clipKey>.wav
     *   2) previously fetched Fish Audio clip cached on disk
     *   3) live Fish Audio synthesis (key + voice id from BuildConfig)
     *   4) on-device TextToSpeech
     */
    fun speak(role: Role, text: String, clipKey: String? = null, queueAdd: Boolean = false) {
        // Dynamic (clipKey-less) lines still get a stable cache key from their text.
        val key = clipKey ?: "dyn_${(role.name + "|" + text).hashCode()}"
        // Nothing gets cut mid-line. Navigation/engineering just queue AHEAD of science.
        val highPriority = role != Role.SCIENCE
        Log.i(TAG, "speak ${role.name} key=$key priority=$highPriority")
        if (playBundled(role, key, highPriority)) return
        if (playFile(fishCacheFile(role, key), highPriority)) return
        if (BuildConfig.FISH_API_KEY.isNotBlank() && voiceIdFor(role).isNotBlank()) {
            fetchFishThenPlay(role, text, key, highPriority)
            return
        }
        speakTts(role, text, role == Role.SCIENCE)
    }

    private fun voiceIdFor(role: Role): String = when (role) {
        Role.NAVIGATION -> BuildConfig.FISH_VOICE_NAVIGATION
        Role.SCIENCE -> BuildConfig.FISH_VOICE_SCIENCE
        Role.ENGINEERING -> BuildConfig.FISH_VOICE_ENGINEERING
        Role.COMPUTER -> BuildConfig.FISH_VOICE_SCIENCE
    }

    private fun fishCacheFile(role: Role, key: String) =
        File(context.cacheDir, "fish_${role.folder}_$key.mp3")

    private fun fetchFishThenPlay(role: Role, text: String, key: String, interrupt: Boolean) {
        Thread {
            val bytes = FishAudioClient.synthesize(
                BuildConfig.FISH_API_KEY, BuildConfig.FISH_MODEL, voiceIdFor(role), text
            )
            main.post {
                if (bytes != null && bytes.size > 256) {
                    val f = fishCacheFile(role, key)
                    runCatching { f.writeBytes(bytes) }
                    if (!playFile(f, interrupt)) speakTts(role, text, role == Role.SCIENCE)
                } else {
                    speakTts(role, text, role == Role.SCIENCE)
                }
            }
        }.apply { isDaemon = true }.start()
    }

    private fun speakTts(role: Role, text: String, queueAdd: Boolean) {
        val engine = tts ?: return
        if (!ready) return
        engine.setPitch(role.pitch)
        engine.setSpeechRate(role.rate)
        pickVoice(engine, role)
        // Queue (never flush) so TTS lines don't cut each other off either.
        engine.speak(text, TextToSpeech.QUEUE_ADD, null, "crew_${role.name}")
    }

    /** Copy a bundled asset clip to cache and play it. False if the asset is absent. */
    private fun playBundled(role: Role, key: String, interrupt: Boolean): Boolean {
        val cacheFile = File(context.cacheDir, "voice_${role.folder}_$key.wav")
        return try {
            if (!cacheFile.exists() || cacheFile.length() == 0L) {
                context.assets.open("voice/${role.folder}/$key.wav").use { input ->
                    cacheFile.outputStream().use { output -> input.copyTo(output) }
                }
            }
            playFile(cacheFile, interrupt)
        } catch (e: Exception) {
            false // no bundled clip
        }
    }

    /** Queue or immediately play an on-disk clip. False if missing/empty. */
    private fun playFile(file: File, highPriority: Boolean): Boolean {
        if (!file.exists() || file.length() < 128L) return false
        if (!busy) {
            startClip(file)                       // nothing playing -> play immediately
        } else {
            // Never cut a clip in progress. Priority only sets queue ORDER:
            // navigation/engineering jump ahead of any queued science.
            if (highPriority) clipQueue.addFirst(file) else clipQueue.addLast(file)
            while (clipQueue.size > 4) clipQueue.removeLast()
        }
        return true
    }

    private fun startClip(file: File) {
        runCatching { player?.release() }
        val mp = MediaPlayer()
        try {
            mp.setDataSource(file.absolutePath)
        } catch (e: Exception) {
            busy = false; playNextQueued(); return
        }
        mp.setOnCompletionListener { it.release(); busy = false; playNextQueued() }
        mp.setOnErrorListener { p, _, _ -> runCatching { p.release() }; busy = false; playNextQueued(); true }
        mp.setOnPreparedListener { it.start() }
        mp.prepareAsync()
        player = mp
        busy = true
    }

    private fun playNextQueued() {
        val next = clipQueue.removeFirstOrNull() ?: return
        startClip(next)
    }

    private fun pickVoice(engine: TextToSpeech, role: Role) {
        val voices = runCatching {
            engine.voices?.filter { it.locale?.language == Locale.US.language && !it.isNetworkConnectionRequired }
        }.getOrNull()?.sortedBy { it.name } ?: return
        if (voices.isEmpty()) return
        runCatching { engine.voice = voices[role.voiceIndex % voices.size] }
    }

    fun shutdown() {
        runCatching { tts?.stop(); tts?.shutdown() }
        tts = null
        ready = false
        clipQueue.clear()
        busy = false
        runCatching { player?.release() }
        player = null
    }
}
